export default {
  "gen-1-pokemon": "Gen 1 Pokemon",
  "gen-2-pokemon": "Gen 2 Pokemon",
  "gen-3-pokemon": "Gen 3 Pokemon",
  "gen-4-pokemon": "Gen 4 Pokemon",
  "gen-5-pokemon": "Gen 5 Pokemon",
  "gen-6-pokemon": "Gen 6 Pokemon",
  "gen-7-pokemon": "Gen 7 Pokemon",
  "gen-8-pokemon": "Gen 8 Pokemon",
  "gen-9-pokemon": "Gen 9 Pokemon",
  "gen-1-legendary-pokemon": "Gen 1 Legendary Pokemon",
  "gen-2-legendary-pokemon": "Gen 2 Legendary Pokemon",
  "gen-3-legendary-pokemon": "Gen 3 Legendary Pokemon",
  "gen-4-legendary-pokemon": "Gen 4 Legendary Pokemon",
  "gen-5-legendary-pokemon": "Gen 5 Legendary Pokemon",
  "gen-6-legendary-pokemon": "Gen 6 Legendary Pokemon",
  "gen-7-legendary-pokemon": "Gen 7 Legendary Pokemon",
  "gen-8-legendary-pokemon": "Gen 8 Legendary Pokemon",
  "gen-9-legendary-pokemon": "Gen 9 Legendary Pokemon",
  "gen-1-mythical-pokemon": "Gen 1 Mythical Pokemon",
  "gen-2-mythical-pokemon": "Gen 2 Mythical Pokemon",
  "gen-3-mythical-pokemon": "Gen 3 Mythical Pokemon",
  "gen-4-mythical-pokemon": "Gen 4 Mythical Pokemon",
  "gen-5-mythical-pokemon": "Gen 5 Mythical Pokemon",
  "gen-6-mythical-pokemon": "Gen 6 Mythical Pokemon",
  "gen-7-mythical-pokemon": "Gen 7 Mythical Pokemon",
  "gen-8-mythical-pokemon": "Gen 8 Mythical Pokemon",
  "gen-9-mythical-pokemon": "Gen 9 Mythical Pokemon"
}
